### ISSUE TITLE
Unauthorized: HTTP ERROR 401

### ISSUE THREAD

**Issue by Niramo** [elexis/elexis-server#21]
I tried to install Elexis-Server, but when I try to open the Local Page there's always the following Error:

_HTTP ERROR 401
Problem accessing /fhir/Patient. Reason:

    Unauthorized
Powered by Jetty:// 9.3.9.v20160517_

The Server is running on a Windows 10 Computer.

There are no errors in the Error-Log except when I try to install the FHIR Feature (es_p2 features install info.elexis.server.fhir.rest.core.feature.feature.group):
_elexis_server\configuration\org.eclipse.osgi\88\0\.cp\jWinHttp-1.0.0.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform (...)_

**Comment by col-panic** [comment]
This is actually not a bug :) You have to be authorized as a user with Role FHIR to be able to access the resp. API. This is not yet well documented, but you can see the general approach in https://github.com/elexis/elexis-server/blob/master/tests/es.core.rest.test/src/info/elexis/server/core/rest/test/serversetup/SetupTest.java 

If you just want to test the FHIR api .. please use the 1.5 branch for the moment being! Documentation will be made available as soon as possible!

**Comment by Niramo** [comment]
Thank you, it works!
Is there a documentation of the supported commands? It seems like these _[Condition, MedicationRequest, Organization, Patient, ProcedureRequest, Coverage, PractitionerRole, CodeSystem, Practitioner, AllergyIntolerance, FamilyMemberHistory, StructureDefinition, Observation, Encounter, OperationDefinition, Claim]_ are supported, but I didn't find a list of which parameters should/can be given

**Comment by col-panic** [comment]
Not at the moment, but in https://github.com/elexis/elexis-server/tree/master/bundles/es.fhir.rest.core/src/es/fhir/rest/core/resources you find the resp. resource implementation classes. So just check out there - if you can assemble a list of specific commands you need we may take care of it.

**Comment by col-panic** [comment]
Documentation currently being developed in https://github.com/elexis/elexis-server/wiki/SMART-on-FHIR
