### ISSUE TITLE
Synchronisation  problem with TOTP

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-server#22]
When a docker container with Elexis Server runs over an extended period of time, there seems to be a time synchronization problem: The next day, 2 Factor authentication fails consistently. Only restarting the container resolves the issue and allows login again.

This is consistently reproducable on my MacBook. Didn't test other systems up to now. 

I'm not sure how to find out the exact reason for this behaviour, since there are no error messages besides "The system was unable to log you in. Please try again."

**Comment by col-panic** [comment]
Interesting. Might be a timing problem between the host and the container?! TOTP requires time synchronicity of +/- 30 seconds. Will have to check!

Von meinem iPhone gesendet

**Comment by rgwch** [comment]
Could you write out current system time as the last line in the console output when launching the server?

**Comment by col-panic** [comment]
I think thats not necessary, as you can do it on demand. Take the following example, I fetch the container id of my running instance and then execute the date command in it

````
Marcos-MacBook-Pro:~ marco$ docker ps
CONTAINER ID        IMAGE                   COMMAND               CREATED             STATUS              PORTS                                                                    NAMES
a2bfd07a3ab6        medevit/elexis-server   "/elexis-server.sh"   About an hour ago   Up 39 minutes       0.0.0.0:7234->7234/tcp, 0.0.0.0:8380->8380/tcp, 0.0.0.0:8480->8480/tcp   vibrant_hypatia
Marcos-MacBook-Pro:~ marco$ docker exec -it a2bfd07a3ab6 /bin/date
Wed May  2 15:14:03 CEST 2018
````

Could you try this once the error occurs and compare it to your local datetime?

**Comment by col-panic** [comment]
https://redmine.medelexis.ch/issues/11376

**Comment by col-panic** [comment]
This problem seems to be limited to OS X see https://docs.docker.com/docker-for-mac/troubleshoot/#known-issues

````
If your system does not have access to an NTP server, then after a hibernate the time seen by Docker for Mac may be considerably out of sync with the host. Furthermore, the time may slowly drift out of sync during use. To manually reset the time after hibernation, run:

docker run --rm --privileged alpine hwclock -s
Or, to resolve both issues, you can add the local clock as a low-priority (high stratum) fallback NTP time source for the host. To do this, edit the host’s /etc/ntp-restrict.conf to add:

server 127.127.1.1              # LCL, local clock
fudge  127.127.1.1 stratum 12   # increase stratum
Then restart the NTP service with:

sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
sudo launchctl load /System/Library/LaunchDaemons/org.ntp.ntpd.plist
````

I don't think that anybody is going to productively host ES on OS X. I am currently reluctant to add an NTP client to the docker instance for just this reason.

What do you think?

**Comment by rgwch** [comment]
Thanks for finding out! That workaround should be ok for me.
If someone wants to run es productively on macOS, they probably won't hibernate. And if they absolutely want, they can still modify the docker image or run es without docker at all.
