### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-server#23]
When I try to restart an existing docker container with elexis-server (`docker start -ia elexis-server`) everything seems to go normal, at the end there's a " A FHIR has been lit on this server" message, but trying to connect http://localhost:8380/openid gives a 404.

The log is attached here
[server-startup.log](https://github.com/elexis/elexis-server/files/1969780/server-startup.log)

Any ideas?

**Comment by col-panic** [comment]
Seems like the demo db is corrupt! Additionally, there might be a problem due to the fact that the elexis-server and the openid server use different h2.versions

**Comment by rgwch** [comment]
What is the correct way to shut down the elexis-server-container? I usually just apply ctrl-C. Probably this corrupts the database. Is there a better way?

**Comment by col-panic** [comment]
That is the correct way - it is only wrongly implemented ;)

**Comment by col-panic** [comment]
The original demoDB fetched at startup was corrupt. Please delete all images and start with a fresh elexis-server docker container. Please inform me whether the problem persists!

**Comment by col-panic** [comment]
Full clean:
````
docker rm a3bf1115e332 (whatever the current containers id)
docker rmi medevit/elexis-server
````

**Comment by rgwch** [comment]
At least it says now at the end "deactivating demo database" which might indicate a clean shutdown :-)
I'll test it the next few days and tell about it. Thanks!

**Comment by rgwch** [comment]
problem didn't happen again
