### ISSUE TITLE
Docker: Can't connect really

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-server#27]
I'm trying to run a current elexis-server with the command:

`docker run -e DEMO_MODE='true' -e TZ=Europe/Zurich -p 8380:8380 -p 8480:8480 -p 7234:7234 medevit/elexis-server:latest`

This works and the server fills the console with some zillion messages, ending with

```
2019-01-07 18:07:28,591 INFO  c.uhn.fhir.rest.server.RestfulServer - Scanning type for RESTful methods: class ca.uhn.fhir.rest.server.PageProvider
2019-01-07 18:07:28,595 INFO  c.uhn.fhir.rest.server.RestfulServer - A FHIR has been lit on this server
2019-01-07 18:07:28,910 INFO  i.e.s.c.s.i.JaxRsServletConfiguration - Registered IniShiroFilter filter for /services
2019-01-07 18:07:28.915:INFO:oejsh.ContextHandler:Start Level: Equinox Container: 9732d30e-73b7-47bd-9d49-6dc8be416752: Started o.e.j.s.ServletContextHandler@422182bd{/,null,AVAILABLE}
2019-01-07 18:07:29,035 INFO  info.elexis.server.core.Application - Starting info.elexis.server.core.Application...
2019-01-07 18:07:29,035 INFO  info.elexis.server.core.Application - Settings: TimeZone [Europe/Zurich], user.language [de], user.region [CH]
2019-01-07 18:07:37,165 INFO  o.a.s.s.m.AbstractValidatingSessionManager - Enabling session validation scheduler...
INFO : org.mitre.openid.connect.config.JsonMessageSource - No locale loaded, trying to load from ServletContext resource [/resources/js/locale/en/messages.json]
```

Then, wen I try [http://localhost:8380/services/elexis/connector/v1/status](http://localhost:8380/services/elexis/connector/v1/status) it gives me 404 "not found".
The same happens with [http://localhost:8380/services](http://localhost:8380/services),
This [http://localhost:8380/fhir/Patient?name=TestPatient](http://localhost:8380/fhir/Patient?name=TestPatient) gives a 401 "unauthorized".
This [https://localhost:8480/web/elexis-connector/connection](https://localhost:8480/web/elexis-connector/connection) says: "Database alredy configured".
[http://localhost:8380/openid/](http://localhost:8380/openid/) takes me to the Praxis Dr. Mustemann, but I don't know the Login-Credentials to use. Wenn I Try Administrator/admin it leads me to [https://2dd4117f228b:8480/openid/login](https://2dd4117f228b:8480/openid/login) which isn't an existing site.

What am I missing?

**Comment by col-panic** [comment]
Please do not currently use the latest tag, it is currently not tested and under heavy development! Please try with medevit/elexis-server:1.6 thanks!

**Comment by col-panic** [comment]
There is a deeper problem in this setup: I was hunting the https://2dd411 etc. stuff for myself today! 
This is the hostname of the docker image, which is problematic for several reasons, please have a look at https://github.com/elexis/elexis-server/blob/master/bundles/es.core.jetty.homebundle/LocalhostSSLDevelopment.md

For local development you have to provide a flag like `-Dopenid.issuer=es.localhost` to enforce the parent hostname.

OpenId does only work with HTTPS, so a proper setup is crucial. I will have a look at your problems tommorow and update the doc accordingly - where did you get the resp. steps from?

**Comment by rgwch** [comment]
Same thing with 1.6. 
I used the doc from here: https://github.com/elexis/elexis-server/blob/master/README.md and here: https://github.com/elexis/elexis-server/wiki

**Comment by col-panic** [comment]
Please try with `docker run -h "es.localhost"  -e TZ=Europe/Zurich -e DEMO_MODE='true' -p 8380:8380 -p 8480:8480 -p 7234:7234 medevit/elexis-server:1.6` the login credentials you find [here](https://github.com/elexis/elexis-server/wiki/SMART-on-FHIR#demo-mode-login) should work.

**Comment by rgwch** [comment]
Ok,thanks. That way it starts and I can OAuth. The informative links (e.g. 
http://localhost:8380/services/elexis/connector/v1/status) still don't work. But the main problem is: I have to login with 3 factors for test runs. I tried  -e DISABLE_WEB_SECURITY='true' along with -e DEMO_MODE='true', but this doesn't change the behaviour. How can I configure the server to just issue a token without asking anything?

**Comment by col-panic** [comment]
The DEMO_MODE flag only enforces the demo database. If you use the DISABLE_WEB_SECURITY flag, you don't have to fetch a token - the FHIR api will not be protected. 

Please have a look at https://github.com/elexis/elexis-server/blob/1.6/tests/es.core.rest.test/src/info/elexis/server/core/rest/test/serversetup/SetupTest.java this is a setup test that runs on every build, together with configuration - the test names should be self-explanatory! 

You are using 1.6?!

**Comment by rgwch** [comment]
Ok, got it. thanks. Yes 1.6, like this: `docker run -h "es.localhost" -e DEMO_MODE='true' -e TZ=Europe/Zurich -e DISABLE_WEB_SECURITY='true' -p 8380:8380 -p 8480:8480 -p 7234:7234 --name d_elexis-server medevit/elexis-server:1.6`
