### ISSUE TITLE
CORS functionality

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-server#4]
The elexis-server should (at least optionally) include "Access-Control-Allow-Origin"-Headers to allow CORS functionality. Without this, it is cumbersome to access a server with a third-party JavaScript client.

HAPI shows two examples [here](http://hapifhir.io/doc_cors.html)

**Comment by col-panic** [comment]
Will be considered in the course of https://redmine.medelexis.ch/issues/5497

The REST API currently is nothing more but a stub. All steering is done using OSGI telnet console.

**Comment by col-panic** [comment]
In the working for ES 1.4 to be released in the ides of june!

**Comment by col-panic** [comment]
CORS is available in current master.
